
language: java
jdk:
  - openjdk11

sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -ataraveski@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="063f3e4b-ea03-4340-9c0b-7d1d35a91023"